version: "3.9"

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres_pytest
    environment:
      POSTGRES_PASSWORD: ratestask
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
