version: "3.9"

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ratestask
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
